### ISSUE TITLE
Remove dependency on 'slug' field in User model

### ISSUE THREAD

**Issue by stork** [CakeDC/comments#41]
CommentsComponent cnd Commentable behavior require field named 'slug' to be present in used User model - name of custom field used in comments elements should be configurable. Workaround is setting up virtual field in User model.

**Comment by fr0z3nfyr** [comment]
Problem persists... Had to create an unnecessary field "slug" in users table.

**Comment by raponiwalter** [comment]
I still have this issue in version 1.3.1. Had to create an empy slug field on users table.
