### ISSUE TITLE
User model fields (id, (displayfield), slug)

### ISSUE THREAD

**Issue by Raphael85** [CakeDC/comments#88]
Hi,

I need to have access to User.pic attribute in flat.ctp. But the only fields I get from User are User.id,(displayfield) and slug.
I manually changed 'slug' to 'pic' in CommentableBehavior but I guess this is not a good solution..

Do I missed something or is it possible to customize User field via options?

Thanks! I do really appreciate this Plugin :)

**Comment by wtbradshaw** [comment]
What was the solution please? I need to add an additional field into the comments table for 'private' comments...
