### ISSUE TITLE
Comment with multiple post not showing

### ISSUE THREAD

**Issue by hardiksondagar** [CakeDC/comments#92]
I've attached Comment to Post module. For Single post ( eg. url : localhost/posts/view/145 ) it's working fine with CommentWidget. But it's not working on post index page ( url: localhost/posts/index , where all post will be displayed ). How to configure CommentWidget for multiple Post's Comment .

Extra detail:
viewVars in 
1.single post page ( url : localhost/posts/view/id )

```
array(
    'post' => array(
        'Post' => array(
            'id' => '152',
            'body' => 'Some text',
            'user_id' => '1',
        )
         )
    )
```

2.multiple post page ( url : localhost/posts/index )

```
'post' => array(
        (int) 0 => array(
            'Post' => array(
                'id' => '152',
                    'body' => 'Some text',
                'user_id' => '1',
            )
                  ),
         (int) 1 => array(
            'Post' => array(
                'id' => '153',
                'body' => 'Another Text',
                'user_id' => '1',
            )
                  )
       )
```

Error I'm getting is

```
CommentsComponent: missing view variable post or value for primary key id of model Post An Internal Error Has Occurred.
```

**Comment by andrej-griniuk** [comment]
Hi @hardiksondagar,
unfortunately the plugin does not support it at the moment, but PRs are of course welcome.

Cheers,
Andrej

**Comment by Megslalk** [comment]
Closing issue - please reopen if necessary
