### ISSUE TITLE
Post comment by bot

### ISSUE THREAD

**Issue by fr0z3nfyr** [CakeDC/comments#95]
Hi, thanks for a great plugin that works well.

This is not really an issue, I didn't know where else to post!! 
I was wondering if there is a way to auto post a comment whenever my `edit()` action is called on my model. 

Let me try to explain the scenario with an example: Let's say I have a model `Task`; **Comments plugin** attached to default `view()` action. One way of posting comments is obviously by users. Another way(problem in question) is to auto-post a comment whenever the task is edited, say the status is changed(this is more like a log entry being made to comments table). I can have a restricted/blocked user in `users` table(DB) called "bot" whose ID will be used to post the entry.

**Comment by fr0z3nfyr** [comment]
"Bump"

**Comment by andrej-griniuk** [comment]
Hi fr0z3nfyr,
you could to it in your `Task` model `afterSave` callback (http://book.cakephp.org/2.0/en/models/callback-methods.html#aftersave)
Hope this helps.

**Comment by Megslalk** [comment]
This issue will be closed; Please feel free to re-open or create a new issue if you still need assistance. Thanks!
